version: '3.8'

services:
  app:
    build:
      context: ./docker/app
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - backend-network
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    # restart: always
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - backend-network
    depends_on:
      - mysql
      - app

  mysql:
    image: mysql:8
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend-network

volumes:
  mysql:
    driver: local

networks:
  backend-network:
    driver: bridge
