name: Deploy to EC2

on:
  push:
    branches:
      - main  # hoặc branch bạn muốn deploy tự động 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare SSH environment
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H 116.118.50.110 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

          # Pull code về
          ssh -i /tmp/ssh_key root@116.118.50.110 "
              cd /root/projects/music-store-api &&
              git pull origin main
          "
          # Restart Docker container để áp dụng các thay đổi
          ssh -i /tmp/ssh_key root@116.118.50.110 "
            cd /root/projects/music-store-api &&
            docker-compose exec app bash &&
            composer install &&
            php artisan config:cache &&
            php artisan migrate &&
          "
