name: Deploy

on:
  push:
    branches:
      - main  # hoặc branch bạn muốn deploy tự động 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy SSH key
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh  # Tạo thư mục .ssh nếu chưa tồn tại
          echo "$VPS_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Thêm ssh key vào danh sách known_hosts để tránh lỗi xác thực host mới
          ssh-keyscan -H 116.118.50.110 >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@116.118.50.110 << 'EOF'
            cd /var/www/music-store-api
            git pull origin main   # Pull code mới từ GitHub
            composer install
            php artisan config:cache
            php artisan migrate
          EOF
